GroupDjango/GroupDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('course/', include("courses.urls")),
    path('forums/', include("forums.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

GroupDjango/courses/urls.py
from django.urls import path
from .views import *
from .views import CourseNewDetailView, CourseEditDetailView, CourseDeleteDetailView, TopicNewDetailView, DeveloperPageView, TopicEditDetailView, TopicDeleteDetailView, ContentNewDetailView, ContentDetailView

urlpatterns = [
    path('courses/developer/', DeveloperPageView.as_view(), name="developer"), 
    path("courses/list/", CourseListView.as_view(), name="course_list"),
    path("courses/new", CourseNewDetailView.as_view(), name="course_new"),
    path('courses/edit/<int:pk>', CourseEditDetailView.as_view(), name="course_edit"),
    path('courses/delete/<int:pk>', CourseDeleteDetailView.as_view(), name="course_delete"),  
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course_detail"),
    path("courses/<int:pk>/enrol", enrol, name="course_enrol"),
    path("courses/topiclist/<int:pk>/", TopicListView.as_view(), name="topic_list"),
    path("courses/topiclist/add/", TopicNewDetailView.as_view(), name="topic_add"),
    path("courses/topic/<int:pk>/", TopicDetailView.as_view(), name="topic_detail"),
    path('courses/topic/edit/<int:pk>', TopicEditDetailView.as_view(), name="topic_edit"),
    path('courses/topic/delete/<int:pk>', TopicDeleteDetailView.as_view(), name="topic_delete"), 
    path("courses/topic/content/new", ContentNewDetailView.as_view(), name="content_add"),
    path("courses/topic/content/<int:pk>", ContentDetailView.as_view(), name="content_detail"),
    path("courses/topic/content/<int:pk>/true/<int:id>", answer_true, name="answer_true"),
    path("courses/topic/content/<int:pk>/false/<int:id>", answer_false, name="answer_false"),
]

GroupDjango/pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"), 
    path('about/', AboutPageView.as_view(), name="about"), 
]

GroupDjango/courses/models.py
from time import time
from django.db import models
from django.forms import CharField
from django.db.models import Sum

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=50)
    whatHeading = models.CharField(max_length=150, default="wHeading here...")
    whatDescription = models.TextField(max_length=500, default="wDescription here...")
    howHeading = models.CharField(max_length=150, default="hHeading here...")
    howDescription = models.TextField(max_length=500, default="hDescription here...")
    price = models.DecimalField(max_digits=10, decimal_places=2, default=10.00)
    
    template_user_result = models.SmallIntegerField(default=0)
    
    def __str__(self):
        return self.name

    @property
    def count_questions(self):
        return Question.objects.filter(content__topic__course = self).count()


class Topic(models.Model):
    course = models.ForeignKey(Course, on_delete= models.CASCADE)
    name = models.CharField(max_length=50, default="name here...")
    intro = models.TextField(max_length=500, default="intro here...")

    def __str__(self):
        str = self.course.name + ", " + self.name
        return str
    
    @property
    def count_questions(self):
        return Question.objects.filter(content__topic = self).count()

class Content(models.Model):
    topic = models.ForeignKey(Topic, on_delete= models.CASCADE, default=4)
    name = models.CharField(max_length=50, default="name here...")
    explanation = models.TextField(max_length=500, default="explanation here...")
    example = models.TextField(max_length=500, default="example here...")
    minutesToComplete = models.SmallIntegerField(default=8)
    template_user_result = models.SmallIntegerField(default=0)

    def __str__(self):
        str = self.topic.course.name + ", " + self.topic.name + ", " + self.name
        return str

    @property
    def count_questions(self):
        return Question.objects.filter(content = self).count()


class Question(models.Model):
    content = models.ForeignKey(Content, on_delete= models.CASCADE)
    question = models.CharField(max_length=100)
    answer = models.BooleanField()

    def __str__(self):
        str = self.content.topic.course.name + ", " + self.content.topic.name + ", " + self.content.name + ", " + self.question
        return str

GroupDjango/courses/forms.py
# import form class from django
from django import forms
 
# import GeeksModel from models.py
from .models import Topic

class TopicNoteForm(forms.ModelForm):
    def __init__(self, topic_list, *args, **kwargs):
        super(TopicNoteForm, self).__init__(*args, **kwargs)
        self.fields['name'] = forms.ChoiceField(choices=tuple([(name, name) for name in topic_list]))
        #widgets = {'agent': forms.widgets.TextInput(attrs={'readonly': True})}
    class Meta:
        model = Topic
        fields = '__all__'

GroupDjango/courses/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
import requests
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.urls import re_path

from courses.forms import TopicNoteForm

from .models import Course, Question, Topic, Content
from enrolment.models import Result, Enrolment

# Create your views here.


class DeveloperPageView(TemplateView):
    template_name = "courses/developer.html"


class CourseListView(ListView):
    model = Course

    def get(self, request):
        courses = Course.objects.all()
        
        if request.user.is_authenticated:      
            user_results = Result.objects.filter(user=request.user).all()
            enrolments = Enrolment.objects.filter(user=request.user).all()

            for c in courses:
                question_count = c.count_questions
                c.template_user_result = 0
                for e in enrolments:
                    if e.course == c:
                        for a in user_results:
                            if a.question.content.topic.course == c:
                                if a.result==True:
                                    c.template_user_result += 1
                        
                        if question_count > 0:
                            e.grade = int(c.template_user_result / question_count *100 )
                        else:
                            e.grade = 0

            context =  {'courses': courses, 'enrolments': enrolments}
        else:
            context =  {'courses': courses}
                    
        return render(request, 'courses/course_list.html', context)

    def post(self, request):
        courses = Course.objects.all()
        
        if request.user.is_authenticated:      
            user_results = Result.objects.filter(user=request.user).all()
            enrolments = Enrolment.objects.filter(user=request.user).all()

            for c in courses:
                question_count = c.count_questions
                c.template_user_result = 0
                for e in enrolments:
                    if e.course == c:
                        for a in user_results:
                            if a.question.content.topic.course == c:
                                if a.result==True:
                                    c.template_user_result += 1
                        
                        if question_count > 0:
                            e.grade = int(c.template_user_result / question_count *100 )
                        else:
                            e.grade = 0

            context =  {'courses': courses, 'enrolments': enrolments}
        else:
            context =  {'courses': courses}
                    
        return render(request, 'courses/course_list.html', context)



class CourseDetailView(DetailView):
    model = Course
    template_name = "courses/course_detail.html"

    def get(self, request, pk):
        course = Course.objects.get(id=pk)
        topics = Topic.objects.filter(course=course).all()

        contents = Content.objects.filter(topic__course__pk=pk).all()
        print('request.user = ', request.user)
        if request.user.is_authenticated:
            user_results = Result.objects.filter(user=request.user, result=True).all()
            
            for c in contents:
                c.template_user_result = 0
                for a in user_results:
                    if a.question.content == c:
                        c.template_user_result += 1
            context = {'course': course, 'topics': topics, 'contents': contents, 'user_results': user_results}
        else:
            context = {'course': course, 'topics': topics, 'contents': contents}

        return render(request, 'courses/course_detail.html', context)


class CourseNewDetailView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("courses.add_courses")
    model = Course
    #template_name = "courses/course_add.html"
    success_url = "../../../course/courses/list/"
    fields = ["name", "whatHeading", "whatDescription",
              "howHeading", "howDescription", "price"]


class CourseEditDetailView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ("courses.change_courses")
    model = Course
    #template_name = "courses/course_edit.html"
    success_url = "/course/courses/list/"
    fields = ["name", "whatHeading", "whatDescription",
              "howHeading", "howDescription", "price"]


class CourseDeleteDetailView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = ("courses.delete_courses")
    model = Course
    template_name = "courses/course_delete.html"
    success_url = reverse_lazy("course_list")


class TopicListView(DetailView):
    model = Course
    template_name = "courses/topic_list.html"


class TopicNewDetailView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("courses.add_topics")
    model = Topic
    #template_name = "courses/topic_add.html"
    success_url = "/course/courses/list/"
    fields = ["course", "name", "intro"]


class TopicDetailView(DetailView):
    model = Topic
    template_name = "courses/topic_detail.html"
    
    def get(self, request, pk):
        topic = Topic.objects.get(id=pk)
        content = Content.objects.filter(topic__pk=pk).all()
        
        
        if request.user.is_authenticated:
            user_results = Result.objects.filter(user=request.user, result=True).all()

            for c in content:
                c.template_user_result = 0
                for a in user_results:
                    if a.question.content == c:
                        c.template_user_result += 1

        return render(request, 'courses/topic_detail.html', {'content': content,
                                                                'topic': topic})

    
class TopicEditDetailView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ("courses.change_courses")
    model = Topic
    #template_name = "courses/topic_edit.html"
    success_url = "/course/courses/list/"
    fields = ["course", "name", "intro"]


class TopicDeleteDetailView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView, DetailView):
    permission_required = ("courses.delete_courses")
    model = Topic
    template_name = "courses/topic_delete.html"
    success_url = reverse_lazy("course_list")


class ContentDetailView(DetailView):
    model = Content
    template_name = "courses/content_detail.html"

    def get(self, request, pk):
        content = Content.objects.get(pk=pk)
        prev_id= content.id - 1
        next_id= content.id + 1
        result_is_correct = None

        if request.user.is_authenticated:
            user_results = Result.objects.filter(user=request.user).all()
            
            context = {'content': content, 'prev_id': prev_id, 'next_id': next_id, 'result_is_correct': result_is_correct, 'user_results': user_results,}
        else:
            context = {'content': content, 'prev_id': prev_id, 'next_id': next_id, 'result_is_correct': result_is_correct }

        return render(request, 'courses/content_detail.html', context)


class ContentNewDetailView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ("courses.add_topics")
    model = Content
    template_name = "courses/content_add.html"
    success_url = "../../../courses/list/"
    fields = ["topic", "name", "explanation", "example", "minutesToComplete"]


def answer_true(request, id, pk):
    question = get_object_or_404(Question, id=id)
    result_is_correct = None
    
    if question.answer:
        result = Result.objects.update_or_create(
            user=request.user,
            question=question,
            defaults={'result': True})
        result_is_correct = True
    else:
        result = Result.objects.update_or_create(
            user=request.user,
            question=question,
            defaults={'result': False})
        result_is_correct = False

    return JsonResponse({'result_is_correct': result_is_correct})


def answer_false(request, id, pk):
    question = get_object_or_404(Question, id=id)
    result_is_correct = None
    
    if not question.answer:
        result = Result.objects.update_or_create(
            user=request.user,
            question=question,
            defaults={'result': True})
        result_is_correct = True
    else:
        result = Result.objects.update_or_create(
            user=request.user,
            question=question,
            defaults={'result': False})
        result_is_correct = False

    return JsonResponse({'result_is_correct': result_is_correct})


def enrol(request, pk):
    course = get_object_or_404(Course, id=pk)
    
    enrolment = Enrolment.objects.update_or_create(
        user=request.user,
        course=course,
        defaults={'grade': 0})
    
    enrolment.save()

    return JsonResponse({'is_correct': enrolment.access})

GroupDjango/courses/templates/courses/content_add.html
{% extends "base.html" %} {%block content %}

<section class="container">
    <div class="course_container">
        <h1>New Content</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
</section>

{% endblock content %}

GroupDjango/courses/templates/courses/content_detail.html
{% extends 'courses/course_base.html' %}

{% block title %} 
    {{content.topic.course.name}}|{{content.topic.name}}|{{content.name}}
{% endblock title %} 

{% block course_header %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading_white">#Python Beginners</h1>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block course_content %}
    <section class="container">
        <div class="course_container">
            <div class="course_content_container">
                <div class="course_course_intro_container">
                    <p class="content_detail_topic_title">
                        {{content.topic}} 
                        <i class="fas fa-caret-right"></i>
                    </p>
                    <h1 class="course_heading">{{ content.name }}</h1>
                    <p class="course_border"><p>
                    <span class="course_progressbar_title">
                        <i class="far fa-clock" id="purple"></i>
                        Expected time: {{ content.minutesToComplete }}  min</span>
                </div>
                <h2 class="course_detail_title">Explanation</h2>
                <p class="course_detail_p"> {{ content.explanation }} </p>
                <h2 class="course_detail_title">Examples</h2>
                <p class="course_detail_p"> {{ content.example }} </p>

            </div>
            <br>        
                {% for question in content.question_set.all %}                    
                    {% include 'components/question_card.html' %}
                {% endfor question %}
                
                <a href="{% url 'content_detail' pk=prev_id %}">< Prev</a>
                <a href="{% url 'content_detail' pk=next_id %}" style="float:right">Next ></a>
        </div>
    </section>
{% endblock %}

GroupDjango/courses/templates/courses/course_add.html
{% extends 'courses/course_base.html' %}
{% load crispy_forms_tags %}

{% block bootstrap %}
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock bootstrap %}

{% block title %} 
    Create Course
{% endblock title %} 

{% block course_header %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading">Course Editer</h1>
                </div>
            </div>
        </div>
    </div>

{% endblock course_header %}

{% block course_content %}
    <div class="container">
        <div class="course_form_center">
            <div class="course_form_card">
                <h1 class="course_form_title">Create New Course</h1>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="reg_button" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock course_content %}

GroupDjango/courses/templates/courses/course_base.html
{% extends 'base.html' %}
{% block title %} 
    Course Detail
{% endblock title %} 

{% block content %}

<!-- Course Header -->
    {% block course_header %}{% endblock %}

<!-- Course contents -->
<div class="container">
    {% block course_content %}{% endblock %}
</div>
{% endblock %}

GroupDjango/courses/templates/courses/course_delete.html
{% extends 'courses/course_base.html' %}

{% block title %} 
    Delete Course
{% endblock title %} 

{% block course_content %}
    <div class="course_container">
        <h1 class="forum_form_title">Delete the Course</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <p class="delete_text">Are you sure you want to delete "{{ course.name }}"?</p>
            <button type="submit" class="form_delete_button">Confirm</button>
        </form>
    </div>
</section>

{% endblock course_content %}

GroupDjango/courses/templates/courses/course_detail.html
{% extends 'courses/course_base.html' %}

{% block title %} 
    Course Detail
{% endblock title %} 

{% block course_header %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading_white">Course Information</h1>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block course_content %}
<section class="container">
    <div class="course_container">
        
        <div class="course_content_container">
            <div class="course_course_intro_container">
                <h1 class="course_heading">{{ course.name }}</h1>
                <p class="course_border"><p>
                
                <button class="button_course_register" id="enrol_{{course.id}}" type="button" value="True">
                    Register
                </button>
                <p class="course_price">
                    <span class="container_responsive" style="padding-right:15px">
                        <i class="far fa-clock" id="purple"></i> 5 hours in Total
                    </span>
                    <span>
                        <i class="fas fa-money-bill" id="purple"></i> $ {{ course.price }}
                    </span>
                </p>
            </div>

            <h2 class="course_detail_title"> {{ course.whatHeading }} </h2>
            <p class="course_detail_p"> {{ course.whatDescription }} </p>

            <h2 class="course_detail_title"> {{ course.howHeading }}</h2>
            <p class="course_detail_p"> {{ course.howDescription }} </p>
    
            <h2 class="course_detail_title" style="margin-bottom:10px">{{ course.name }} Topics:</h2>     
            
            <div class="course_detail_flex">       
                {% for topic in topics %}
                    
                    {% include 'components/topic_card.html' %} 
                
                {% endfor topic %}
            <div> 

            {% if user.is_authenticated %}
                {% for group in user.groups.all %}
                    {% if group.name == "Developer" %}
                        <h3 class="course_add_link">
                            <a href="{% url 'course_edit' course.pk %}">
                                <i class="fas fa-edit" id="purple"></i> Edit Course
                            </a>
                        </h3>
                        <h3 class="course_add_link">
                            <a href="{% url 'course_delete' course.pk %}">
                                <i class="fas fa-trash-alt" id="orange"></i> Delete Course
                            </a>
                        </h3>
                        <h3 class="course_add_link">
                            <a href="{% url 'topic_add' %}">
                                <i class="fas fa-plus-circle" id="orange"></i> Add Topic
                            </a>
                        </h3>  
                        
                                                   
                    {% endif %}
                {%endfor%}
            {% endif %}

        </div>
    </div>
</section>

<script>
    $("#enrol_{{course.id}}").click(function () {
         $.ajax({
             type: "POST",
             url: "{% url 'course_enrol' pk=course.id %}",
             data: { 'csrfmiddlewaretoken': '{{csrf_token}}' },
             dataType: "json",
             success: function (r) {
                 alert(r)
             },
             error: function (rs, e) { }
         });
    })
 </script>
{% endblock course_content %}

GroupDjango/courses/templates/courses/course_form.html
{% extends 'courses/course_base.html' %}
{% load crispy_forms_tags %}

{% block bootstrap %}
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock bootstrap %}

{% block title %} 
    Create Course
{% endblock title %} 

{% block course_header %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading_white">Course Editer</h1>
                </div>
            </div>
        </div>
    </div>

{% endblock course_header %}

{% block course_content %}
    <div class="container">
        <div class="course_form_center">
            <div class="course_form_card">
                <h1 class="forum_form_title">
                    {% if not course.pk %}
                        Create a new course
                    {% else%}
                        Update Course
                    {% endif %}
                </h1>

                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="reg_button" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock course_content %}

GroupDjango/courses/templates/courses/course_list.html
{% extends 'courses/course_base.html' %}

{% block title %} 
    Course List 
{% endblock title %}

{% block course_header %}
    {% if user.is_authenticated %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading_white">{{request.user.username}} Course List</h1>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <div class="course_header_container">
            <div class="container">
                <div class="course_header_container">
                    <div>
                        <h1 class="course_heading_white">Various Courses for Coding</h1>

                        <p class="course_header_p">GET IT teams are all experienced developers,<br>
                            We know how to learn and what to do.<br>
                            Our best tutorials has variery with many good sourse.
                        </p>
                    </div>
                        <div>
                            <a class="course_btn_post" href="#">
                                Get Start Studing</a>
                        </div>    
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block course_content %}
    <section class="container">
        <div class="course_container">

            <h1 class="course_heading">
                {% if user.is_authenticated %}
                    {{ user.username }}'s 
                {% endif %}  
                    Course Detail</h1>
            {% for course in courses %}

                {% include 'components/course_card.html' %}    
                
            {% endfor %}

            {% if user.is_authenticated %}
                {% for group in user.groups.all %}
                    {% if group.name == "Developer" %}
                            <h3 class="course_add_link">
                                <a href="{% url 'course_new' %}"><i class="fas fa-plus-circle" id="orange"></i> Add New Course</a>
                            </h3>
                    {% endif %}
                {%endfor%}
                
            {% endif %}
        </div>
    </section>
{% endblock course_content %}

GroupDjango/courses/templates/courses/developer.html
{% extends "base.html" %} 

{% block title %} Home {% endblock title %}

{%block content %}

{% load static %}

<!-- ########################## Contents ########################## -->
<section class="container">
    <div class="course_container">
        <div style="margin-bottom:20px;">
            <h1 class="course_heading">Developer Options</h1>
            <h2 class="course_title"><a href="{% url 'course_new' %}">New Course</a></h2>
            <h2 class="course_title"><a href="{% url 'topic_add' %}">New Topic</a></h2>
            <h2 class="course_title"><a href="{% url 'content_add' %}">New Content</a></h2>
        </div>
    </div>
</section>

{% endblock content %}

GroupDjango/courses/templates/courses/topic_delete.html
{% extends 'courses/course_base.html' %}

{% block title %} 
    Delete Topic
{% endblock title %} 

{% block course_content %}
    <div class="course_container">
        <h1 class="forum_form_title">Delete the Topic</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <p class="delete_text">Are you sure you want to delete "{{ topic.name }}"?</p>
            <button type="submit" class="form_delete_button">Confirm</button>
        </form>
    </div>
</section>
{% endblock course_content %}

GroupDjango/courses/templates/courses/topic_detail.html
{% extends 'courses/course_base.html' %}


{% block title %} 
    Topic Detail
{% endblock title %} 

{% block course_header %}
    <div class="course_header_container">
        <div class="container">
            <div class="course_header_container">
                <div>
                    <h1 class="course_heading_white">#Python Beginners</h1>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block course_content %}
<section class="container">
    <div class="course_container">   
        <div class="course_content_container">
            <div class="course_course_intro_container">
                <h1 class="course_heading">{{ topic.name }}</h1>
                <p class="course_border"><p>
            </div>

            <p class="course_detail_p"> {{ topic.intro }} </p>

            <h2 class="course_detail_title"> {{ course.howHeading }}</h2>
            <p class="course_detail_p"> {{ course.howDescription }} </p>
    

            <h2 class="course_detail_title" style="margin-bottom:10px">{{ course.name }} Topics:</h2>
            
            <div class="course_detail_flex">
                {% for c in content %}
                
                    {% include 'components/content_card.html' %}
        
                {% endfor %}
                <div> 

            {% if user.is_authenticated %}
                {% for group in user.groups.all %}
                    {% if group.name == "Developer" %}
                        <h3 class="course_add_link">
                            <a href="{% url 'topic_edit' topic.pk %}">
                                <i class="fas fa-edit" id="purple"></i> Edit Topic
                            </a>
                        </h3>  
                        <h3 class="course_add_link">
                            <a href="{% url 'topic_delete' topic.pk %}">
                                <i class="fas fa-trash-alt" id="orange"></i> Delete Topic
                            </a>
                        </h3> 
                    {% endif %}
                {%endfor%}
            {% endif %}

        </div>
    </div>
</section>
{% endblock course_content %}

GroupDjango/courses/templates/courses/topic_list.html
{% extends "base.html" %}
{% block title %} 
    Topics
{% endblock title %} 

{% block content %}
<section class="container">
    <div class="course_container">
    {% if user.is_authenticated %}
        {% for group in user.groups.all %}
            {% if group.name == "Developer" %}
                <div style="margin-bottom:20px;">
                    <h1 class="course_heading">Developer Options</h1>
                    <h2 class="course_title"><a href="{% url 'course_new' %}">Add New Topic</a></h2>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <h1 class="course_heading">{{course.name}} Topics</h1>
    <p class="border"><p>

    {% for topic in course.topic_set.all %}
        <h2 class="topic_title">{{ topic.name }} </h2>
        <p class="topic_p"> {{ topic.intro }} </p>
    {% endfor topic %}
    
    </div>
</section>
{% endblock content %}