GroupDjango/GroupDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('course/', include("courses.urls")),
    path('forums/', include("forums.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

GroupDjango/forums/urls.py
# FORUMS URL.PY
from django.urls import path
from . import views

app_name = 'forums'

urlpatterns = [
    path('', views.ListForums.as_view(), name='all'),
    path("detail/<pk>/", views.SingleForum.as_view(), name='single'),
    path('selected/<str:user>/',
         views.ListSelectedUserForums.as_view(), name='selected_user'),
    path('unsolved/',
         views.ListSelectedUnsolvedForums.as_view(), name='selected_unsolved'),
    path("new/", views.CreateForum.as_view(), name='create'),
    path("update/<pk>/", views.UpdateForum.as_view(), name='update'),

    path('comment/<pk>/', views.add_comment_to_post,
         name='add_comment_to_post'),
    path('comment/<pk>/remove/', views.comment_remove, name='comment_remove'),
]

GroupDjango/pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"), 
    path('about/', AboutPageView.as_view(), name="about"), 
]

GroupDjango/forums/models.py
from django.contrib.auth import get_user_model
from django import template
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings


User = get_user_model()
register = template.Library()


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = models.IntegerField(default=0)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name


class Forum(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    category = models.ForeignKey(
        Category, related_name="categories", on_delete=models.CASCADE)
    description = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    is_closed = models.BooleanField(default=False)
    user = models.ForeignKey(User, related_name='forums',
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("forums:single", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-created_at"]


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='Comments',
                             on_delete=models.CASCADE)
    forum = models.ForeignKey(
        Forum, related_name='comments', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    message = models.TextField()

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("forums:single", kwargs={"pk": self.pk})

    class Meta:
        ordering = ['created_at']

GroupDjango/forums/forms.py
from django import forms
from forums.models import Comment


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('message',)

        widgets = {
            'message': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

GroupDjango/forums/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.db.models import Count

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import Http404
from django.views import generic
from forums.models import Forum, Category, Comment
from forums.forms import CommentForm
from braces.views import SelectRelatedMixin


from django.contrib.auth.decorators import login_required

from django.contrib.auth import get_user_model
User = get_user_model()


class CreateForum(LoginRequiredMixin, generic.CreateView):
    model = Forum
    fields = ('title', 'category', 'description')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdateForum(LoginRequiredMixin, generic.UpdateView):
    model = Forum
    fields = ('title', 'description', 'is_closed')


class SingleForum(generic.DetailView):
    model = Forum

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

    def get_comment_count(self):
        comment_counter = Comment.object.annotate(count('forum'))
        comment_count = comment_counter[self]
        return comment_count


class ListForums(generic.ListView):
    model = Forum

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class ListSelectedUserForums(generic.ListView):
    model = Forum
    template_name = 'forums/forum_list_selected_user.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("forums").get(
                username__iexact=self.kwargs.get("user")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.forums.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class ListSelectedUnsolvedForums(generic.ListView):
    model = Forum
    template_name = 'forums/forum_list_selected_unsolve.html'

    def get_queryset(self):
        return Forum.objects.filter(is_closed='False')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


######################################################################################################

######################################################################################################


@login_required
def add_comment_to_post(request, pk):
    forum = get_object_or_404(Forum, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.forum = forum
            comment.user = user
            comment.save()
            return redirect('forums:single', pk=forum.pk)
    else:
        form = CommentForm()
    return render(request, 'forums/comment_form.html', {'form': form})


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    forum_pk = comment.forum.pk
    comment.delete()
    return redirect('forums:single', pk=forum_pk)

GroupDjango/forums/templates/forums/_forum_simple_header.html
<div class="forum_container">
    <div class="container">
        <div class="forum_header_container">
            <h1 class="forum_heading">Q&amp;A Forum</h1>                 
        </div>
    </div>
</div>

GroupDjango/forums/templates/forums/comment_form.html
{% extends 'forums/forum_base.html' %}
{% load crispy_forms_tags %}

{% block bootstrap %}
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock bootstrap %}

{% block forum_header %}
    {% include "forums/_forum_simple_header.html" %}
{% endblock %}

{% block form_content %}
    <div class="container">
        <div class="forum_form_center">
            <div class="forum_form_card">
                <h1 class="forum_form_title">New Comment</h1>

                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="reg_button" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

GroupDjango/forums/templates/forums/forum_base.html
{% extends 'base.html' %}
{% block title %} 
    Q&amp;A forum
{% endblock title %} 


{% block content %}

<!-- Q&A Header -->
    {% block forum_header %}{% endblock %}

<!-- Q&A contents -->
<div class="container">
    {% block form_content %}{% endblock %}
    <div class="forum_main_flex">
        <div class="forum_main_flex_contents">
            {% block preforum %}{% endblock %}
            {% block forum_content %}{% endblock %}
            {% block post_content %}{% endblock %}
        </div>
        <div class="forum_main_flex_category">
            {% block category %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

GroupDjango/forums/templates/forums/forum_detail.html
{% extends 'forums/forum_base.html' %}
{% block forum_header %}
    {% include "forums/_forum_simple_header.html" %}
{% endblock %}

{% block forum_content %}
    <div class="card_forum_detail">
        <h2 class="forum_list_title">{{forum.title}}</h2>
        <p class="form_list_text">{{forum.description}}</p>
        <hr>
        <div class="forum_list_detail">
            <span id="tag">{{forum.category}}</span>
            <span><i class="fas fa-user"></i> {{forum.user}}</span>
            <span><i class="far fa-clock"></i> {{forum.created_at}}</span>
            <span><i class="far fa-comments"></i> 5 </span>
            {% if forum.is_closed != true %}
                <span><i class="far fa-frown-open"></i> Unsolved</span>
            {% else %}
                <span><i class="fas fa-check" style="color:#F5C03B;"></i> Solved</span>
            {% endif %}         
        </div>

        {% if forum.user|stringformat:'s' == user.get_username|stringformat:'s'  %}
            <div>
                <a href="{% url 'forums:update' pk=forum.pk %}" class='add_coment'>
                    <i class="fas fa-edit" id="purple"></i> Update the post</a><br>
            </div>
        {% endif %} 

    </div>
{% endblock %}


{% block post_content %}
    <div class="card_comment">
        <div class="comment_title_container">
            <div><h2 class="forum_list_title">Comments</h2></div>
            {% if user.is_authenticated %}
                <div>
                    <a href="{% url 'forums:add_comment_to_post' pk=forum.pk %}" class='add_coment'>
                        <i class="fas fa-plus-circle" id="orange"></i> Post a Comment</a><br>
                </div>
            {% endif %}
        </div>
        <hr>
        {% if comment|length == 0 %}
            <p class="form_list_text_no_comment">No comment!</p>
        {% endif %}

        {% for comment in forum.comments.all %}
            <div class="forum_comment_detail">
                <p class="form_list_text">{{ comment.message }}</p>

                <span><i class="fas fa-user"></i> {{ comment.user }}</span>
                <span><i class="far fa-clock"></i> {{ comment.created_at }}</span>
                {% if comment.user|stringformat:'s' == user.get_username|stringformat:'s' %}
                <a class="comment_delete" href="{% url 'forums:comment_remove' pk=comment.pk %}">
                    <i class="fas fa-trash-alt" id="orange"></i> Delete</a>
                {% endif %}
            </div>
            <hr class="coment_line">
        {% endfor %}
    </div>
{% endblock %}

{% block category %}
<div>
    <div class="card_forum_detail_search">
        {% if user.is_authenticated %}
            <h3 class="forum_cat_title">Hi {{ user.username }}!</h3>
            <hr>
            <div class="forum_cat_list_container">
                <a class="forum_user_box" href="{% url 'forums:create' %}">
                    <i class="fas fa-edit"></i> Post New Question</a>
                <a class="forum_user_box" href="{% url 'forums:selected_user' user.username %}">Your Post List</a>
                <a class="forum_user_box" href="#">Your Comment List</a>
            </div>
        {% else %}
        <h3 class="forum_cat_title">Search</h3>
        <hr>
        <br>            
        {% endif %}
        
        <form class="forum_search_right" action="#">
            <input type="text" name="search"><button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>

    <div class="card_forum">
        <h3 class="forum_cat_title">Category</h3>
        <hr>
        <div class="forum_cat_list_container">
            {% for c in category %}
            <a class="forum_cat_box" href="#">{{c.name}} &#40; 7 &#41;</a>
            {% endfor %}
        </div>
    <div>
</div>
{% endblock %}

GroupDjango/forums/templates/forums/forum_form.html
{% extends "forums/forum_base.html" %}
{% load crispy_forms_tags %}

{% block bootstrap %}
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock bootstrap %}

{% block forum_header %}
    {% include "forums/_forum_simple_header.html" %}
{% endblock %}

{% block form_content %}
    <div class="container">
        <div class="forum_form_center">
            <div class="forum_form_card">
                <h1 class="forum_form_title">
                    {% if not forum.pk %}
                        Post a new question
                    {% else%}
                        Update forum
                    {% endif %}
                </h1>

                <form method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="reg_button" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

GroupDjango/forums/templates/forums/forum_list.html
{% extends 'forums/forum_base.html' %}

{% block forum_header %}
    <div class="forum_container">
        <div class="container">
            <div class="forum_header_container">
                <div>
                    <h1 class="forum_heading">We are here to help!</h1>

                    <p class="forum_header_p">This Q&amp;A forum is a great place to share your problem and <br>
                        tackle it togather to find the solution.<br>
                        Search a solution or post your problem here.
                    </p>
                </div>
                <div class="forum_search_container">
                    <form class="forum_search" action="/action_page.php">
                        <input type="text" name="search">
                        <button type="submit"> <i class="fa fa-search"></i> </button>
                    </form>
                </div>
                
                    {% if user.is_authenticated %}
                    <div>
                        <a class="forum_btn_post" href="{% url 'forums:create' %}">
                            Post New Question</a>
                    </div>
                    {% endif %}         
            </div>
        </div>
    </div>
{% endblock %}


{% block preforum %}
    <nav  class="forum_navbar">
        <ul>
            <li><a id="active" href="{% url 'forums:all' %}">Recent Questions</a></li>
            <li><a href="#">Most Responses</a></li>
            <li><a href="{% url 'forums:selected_unsolved' %}">Unsolved</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'forums:selected_user' user.username %}">Your List</a></li>
            {% endif %}
          </ul>
    </nav>
{% endblock %}


{% block forum_content %}
    <div>
        {% for forum in forum_list %}
        <div class="card_forum">
            
            <h2 class="forum_list_title">
                <a class='list' href="{% url 'forums:single' pk=forum.pk %}">{{forum.title}}</a></h2>
            <p class="form_list_text">{{forum.description|truncatewords:50}}</p>
            <hr>
            <div class="forum_list_detail">
                <span id="tag">{{forum.category}}</span>
                <span><i class="fas fa-user"></i> {{forum.user}}</span>
                <span><i class="far fa-clock"></i> {{forum.created_at}}</span>
                <span><i class="far fa-comments"></i> 7</span>
                {% if forum.is_closed == True %}
                    <span><i class="fas fa-check" style="color:green;"></i> Solved</span>            
                {% else %}
                    <span><i class="far fa-frown-open"></i> Unsolved</span>
                {% endif %}     
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block category %}
    <div>
        {% if user.is_authenticated %}
            <div class="card_forum">
                <h3 class="forum_cat_title">Hi {{ user.username }}!</h3>
                <hr>
                <div class="forum_cat_list_container">
                    <a class="forum_user_box" href="{% url 'forums:create' %}">
                        <i class="fas fa-edit"></i> Post New Question</a>
                    <a class="forum_user_box" href="{% url 'forums:selected_user' user.username %}">Your Post List</a>
                    <a class="forum_user_box" href="#">Your Comment List</a>
                </div>    
            </div>       
        {% endif %}

        <div class="card_forum">
            <h3 class="forum_cat_title">Category</h3>
            <hr>
            <div class="forum_cat_list_container">
                {% for c in category %}
                <a class="forum_cat_box" href="#">{{c.name}} &#40; 5 &#41;</a>
                {% endfor %}
            </div>
        <div>
    </div>
{% endblock %}

GroupDjango/forums/templates/forums/forum_list_selected_unsolve.html
{% extends 'forums/forum_base.html' %}

{% block forum_header %}
    {% include "forums/_forum_simple_header.html" %}
{% endblock %}


{% block preforum %}
    <nav  class="forum_navbar">
        <ul>
            <li><a href="{% url 'forums:all' %}">Recent Questions</a></li>
            <li><a href="#">Most Responses</a></li>
            <li><a id="active" href="{% url 'forums:selected_unsolved' %}">Un Solved</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'forums:selected_user' user.username %}">Your List</a></li>
            {% endif %}
          </ul>
    </nav>
{% endblock %}


{% block forum_content %}
    <div>
        {% for forum in forum_list %}
        <div class="card_forum">
            
            <h2 class="forum_list_title">
                <a class='list' href="{% url 'forums:single' pk=forum.pk %}">{{forum.title}}</a></h2>
            <p class="form_list_text">{{forum.description|truncatewords:50}}</p>
            <hr>
            <div class="forum_list_detail">
                <span id="tag">{{forum.category}}</span>
                <span><i class="fas fa-user"></i> {{forum.user}}</span>
                <span><i class="far fa-clock"></i> {{forum.created_at}}</span>
                <span><i class="far fa-comments"></i> 7</span>
                {% if forum.is_closed == True %}
                    <span><i class="fas fa-check" style="color:green;"></i> Solved</span>            
                {% else %}
                    <span><i class="far fa-frown-open"></i> Unsolved</span>
                {% endif %}     
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block category %}
<div>
    <div class="card_forum">
        {% if user.is_authenticated %}
            <h3 class="forum_cat_title">Hi {{ user.username }}!</h3>
            <hr>
            <div class="forum_cat_list_container">
                <a class="forum_user_box" href="{% url 'forums:create' %}">
                    <i class="fas fa-edit"></i> Post New Question</a>
                <a class="forum_user_box" href="{% url 'forums:selected_user' user.username %}">Your Post List</a>
                <a class="forum_user_box" href="#">Your Comment List</a>
            </div>
        {% else %}
        <h3 class="forum_cat_title">Search area</h3>
        <hr>
        <br>            
        {% endif %}
        
        <form class="forum_search_right" action="#">
            <input type="text" name="search"><button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>

    <div class="card_forum">
        <h3 class="forum_cat_title">Category</h3>
        <hr>
        <div class="forum_cat_list_container">
            {% for c in category %}
            <a class="forum_cat_box" href="#">{{c.name}} &#40; 5 &#41;</a>
            {% endfor %}
        </div>
    <div>
</div>
{% endblock %}

GroupDjango/forums/templates/forums/forum_list_selected_user.html
{% extends 'forums/forum_base.html' %}

{% block forum_header %}
    {% include "forums/_forum_simple_header.html" %}
{% endblock %}


{% block preforum %}
    <nav  class="forum_navbar">
        <ul>
            <li><a href="{% url 'forums:all' %}">Recent Questions</a></li>
            <li><a href="#">Most Responses</a></li>
            <li><a href="{% url 'forums:selected_unsolved' %}">Un Solved</a></li>
            <li><a id="active" href="{% url 'forums:selected_user' user.username %}">Your List</a></li>
          </ul>
    </nav>
{% endblock %}


{% block forum_content %}
    <div>
        {% for forum in forum_list %}
        <div class="card_forum">
            
            <h2 class="forum_list_title">
                <a class='list' href="{% url 'forums:single' pk=forum.pk %}">{{forum.title}}</a></h2>
            <p class="form_list_text">{{forum.description|truncatewords:50}}</p>
            <hr>
            <div class="forum_list_detail">
                <span id="tag">{{forum.category}}</span>
                <span><i class="fas fa-user"></i> {{forum.user}}</span>
                <span><i class="far fa-clock"></i> {{forum.created_at}}</span>
                <span><i class="far fa-comments"></i> 7</span>
                {% if forum.is_closed == True %}
                    <span><i class="fas fa-check" style="color:green;"></i> Solved</span>            
                {% else %}
                    <span><i class="far fa-frown-open"></i> Unsolved</span>
                {% endif %}     
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

{% block category %}
<div>
    <div class="card_forum">
        {% if user.is_authenticated %}
            <h3 class="forum_cat_title">Hi {{ user.username }}!</h3>
            <hr>
            <div class="forum_cat_list_container">
                <a class="forum_user_box" href="{% url 'forums:create' %}">
                    <i class="fas fa-edit"></i> Post New Question</a>
                <a class="forum_user_box" href="{% url 'forums:selected_user' user.username %}">Your Post List</a>
                <a class="forum_user_box" href="#">Your Comment List</a>
            </div>
        {% else %}
        <h3 class="forum_cat_title">Search area</h3>
        <hr>
        <br>            
        {% endif %}
        
        <form class="forum_search_right" action="#">
            <input type="text" name="search"><button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>

    <div class="card_forum">
        <h3 class="forum_cat_title">Category</h3>
        <hr>
        <div class="forum_cat_list_container">
            {% for c in category %}
            <a class="forum_cat_box" href="#">{{c.name}} &#40; 5 &#41;</a>
            {% endfor %}
        </div>
    <div>
</div>
{% endblock %}